/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.hackathon.raspberrypi.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RaspberryPi service. Represents a row in the &quot;Hackathon_RaspberryPi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.hackathon.raspberrypi.model.impl.RaspberryPiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.hackathon.raspberrypi.model.impl.RaspberryPiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RaspberryPi
 * @see com.liferay.portal.hackathon.raspberrypi.model.impl.RaspberryPiImpl
 * @see com.liferay.portal.hackathon.raspberrypi.model.impl.RaspberryPiModelImpl
 * @generated
 */
@ProviderType
public interface RaspberryPiModel extends BaseModel<RaspberryPi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a raspberry pi model instance should use the {@link RaspberryPi} interface instead.
	 */

	/**
	 * Returns the primary key of this raspberry pi.
	 *
	 * @return the primary key of this raspberry pi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this raspberry pi.
	 *
	 * @param primaryKey the primary key of this raspberry pi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this raspberry pi.
	 *
	 * @return the uuid of this raspberry pi
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this raspberry pi.
	 *
	 * @param uuid the uuid of this raspberry pi
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the raspberry ID of this raspberry pi.
	 *
	 * @return the raspberry ID of this raspberry pi
	 */
	public long getRaspberryId();

	/**
	 * Sets the raspberry ID of this raspberry pi.
	 *
	 * @param raspberryId the raspberry ID of this raspberry pi
	 */
	public void setRaspberryId(long raspberryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RaspberryPi raspberryPi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RaspberryPi> toCacheModel();

	@Override
	public RaspberryPi toEscapedModel();

	@Override
	public RaspberryPi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}