/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.hackathon.raspberrypi.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.hackathon.raspberrypi.model.RaspberryPi;
import com.liferay.portal.hackathon.raspberrypi.model.RaspberryPiModel;
import com.liferay.portal.hackathon.raspberrypi.model.RaspberryPiSoap;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RaspberryPi service. Represents a row in the &quot;Hackathon_RaspberryPi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link RaspberryPiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RaspberryPiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RaspberryPiImpl
 * @see RaspberryPi
 * @see RaspberryPiModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RaspberryPiModelImpl extends BaseModelImpl<RaspberryPi>
	implements RaspberryPiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a raspberry pi model instance should use the {@link RaspberryPi} interface instead.
	 */
	public static final String TABLE_NAME = "Hackathon_RaspberryPi";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "raspberryId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("raspberryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table Hackathon_RaspberryPi (uuid_ VARCHAR(75) null,raspberryId LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table Hackathon_RaspberryPi";
	public static final String ORDER_BY_JPQL = " ORDER BY raspberryPi.raspberryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Hackathon_RaspberryPi.raspberryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.hackathon.raspberrypi.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.portal.hackathon.raspberrypi.model.RaspberryPi"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.hackathon.raspberrypi.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.portal.hackathon.raspberrypi.model.RaspberryPi"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.portal.hackathon.raspberrypi.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.hackathon.raspberrypi.model.RaspberryPi"),
			true);
	public static final long UUID_COLUMN_BITMASK = 1L;
	public static final long RASPBERRYID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RaspberryPi toModel(RaspberryPiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RaspberryPi model = new RaspberryPiImpl();

		model.setUuid(soapModel.getUuid());
		model.setRaspberryId(soapModel.getRaspberryId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RaspberryPi> toModels(RaspberryPiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<RaspberryPi> models = new ArrayList<RaspberryPi>(soapModels.length);

		for (RaspberryPiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.hackathon.raspberrypi.service.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.portal.hackathon.raspberrypi.model.RaspberryPi"));

	public RaspberryPiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _raspberryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRaspberryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _raspberryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RaspberryPi.class;
	}

	@Override
	public String getModelClassName() {
		return RaspberryPi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("raspberryId", getRaspberryId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long raspberryId = (Long)attributes.get("raspberryId");

		if (raspberryId != null) {
			setRaspberryId(raspberryId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getRaspberryId() {
		return _raspberryId;
	}

	@Override
	public void setRaspberryId(long raspberryId) {
		_raspberryId = raspberryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			RaspberryPi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RaspberryPi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RaspberryPi)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RaspberryPiImpl raspberryPiImpl = new RaspberryPiImpl();

		raspberryPiImpl.setUuid(getUuid());
		raspberryPiImpl.setRaspberryId(getRaspberryId());

		raspberryPiImpl.resetOriginalValues();

		return raspberryPiImpl;
	}

	@Override
	public int compareTo(RaspberryPi raspberryPi) {
		long primaryKey = raspberryPi.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RaspberryPi)) {
			return false;
		}

		RaspberryPi raspberryPi = (RaspberryPi)obj;

		long primaryKey = raspberryPi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		RaspberryPiModelImpl raspberryPiModelImpl = this;

		raspberryPiModelImpl._originalUuid = raspberryPiModelImpl._uuid;

		raspberryPiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<RaspberryPi> toCacheModel() {
		RaspberryPiCacheModel raspberryPiCacheModel = new RaspberryPiCacheModel();

		raspberryPiCacheModel.uuid = getUuid();

		String uuid = raspberryPiCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			raspberryPiCacheModel.uuid = null;
		}

		raspberryPiCacheModel.raspberryId = getRaspberryId();

		return raspberryPiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", raspberryId=");
		sb.append(getRaspberryId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portal.hackathon.raspberrypi.model.RaspberryPi");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>raspberryId</column-name><column-value><![CDATA[");
		sb.append(getRaspberryId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = RaspberryPi.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			RaspberryPi.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _raspberryId;
	private long _columnBitmask;
	private RaspberryPi _escapedModel;
}